title: Nuvempower
description: Apps para negócios
theme: minima
author: Nuvempower
email: contato@nuvempower.com
url: "https://www.nuvempower.com"
baseurl: "" # deixe em branco se estiver usando domínio raiz
