title: Nuvempower
description: Apps para negócios
theme: minima
author: Nuvempower
email: info@nuvempower.com
url: "https://www.nuvempower.com"
baseurl: "" # deixe em branco se estiver usando domínio raiz
theme: jekyll-theme-minimal
